/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redebayesiana.view;

import javax.swing.JLabel;
import redebayesiana.No;

/**
 *
 * @author david
 */
public class NodePanel extends javax.swing.JPanel {
    No node;
    /**
     * Creates new form NodePanel
     */
    public NodePanel() {
        initComponents();
    }

    public No getNode() {
        return node;
    }

    public void setNode(No node) {
        this.node = node;
    }

    
    @Override
    public String toString() {
        return nameNode.getText(); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        belief10 = new javax.swing.JLabel();
        belief00 = new javax.swing.JLabel();
        lambda10 = new javax.swing.JLabel();
        lambda00 = new javax.swing.JLabel();
        piF10 = new javax.swing.JLabel();
        piF00 = new javax.swing.JLabel();
        pi11 = new javax.swing.JLabel();
        pi10 = new javax.swing.JLabel();
        pi01 = new javax.swing.JLabel();
        pi00 = new javax.swing.JLabel();
        nameNode = new javax.swing.JLabel();
        backgroundNode = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        belief10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        belief10.setText("10");
        add(belief10, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 147, 22, -1));

        belief00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        belief00.setText("00");
        add(belief00, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 127, 22, -1));

        lambda10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lambda10.setText("10");
        add(lambda10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 22, -1));

        lambda00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lambda00.setText("00");
        add(lambda00, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 22, -1));

        piF10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piF10.setText("10");
        add(piF10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 50, 20, -1));

        piF00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piF00.setText("00");
        add(piF00, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 33, 20, -1));

        pi11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi11.setText("11");
        add(pi11, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 50, 20, -1));

        pi10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi10.setText("10");
        add(pi10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 20, -1));

        pi01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi01.setText("01");
        add(pi01, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 33, 20, -1));

        pi00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi00.setText("00");
        add(pi00, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 33, 20, -1));

        nameNode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameNode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameNode.setText("Novo nó");
        add(nameNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 150, 20));

        backgroundNode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoNó.png"))); // NOI18N
        add(backgroundNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 170));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getBelief00() {
        return belief00;
    }

    public void setBelief00(String belief00) {
        this.belief00.setText(belief00);;
    }

    public JLabel getBelief10() {
        return belief10;
    }

    public void setBelief10(String belief10) {
        this.belief10.setText(belief10);
    }

    public JLabel getLambda00() {
        return lambda00;
    }

    public void setLambda00(String lambda00) {
        this.lambda00.setText(lambda00);
    }

    public JLabel getLambda10() {
        return lambda10;
    }

    public void setLambda10(String lambda10) {
        this.lambda10.setText(lambda10);
    }

    public JLabel getNameNode() {
        return nameNode;
    }

    public void setNameNode(String nameNode) {
        this.nameNode.setText(nameNode);
    }

    public JLabel getPi00() {
        return pi00;
    }

    public void setPi00(String pi00) {
        this.pi00.setText(pi00);
    }

    public JLabel getPi01() {
        return pi01;
    }

    public void setPi01(String pi01) {
        this.pi01.setText(pi01);
    }

    public JLabel getPi10() {
        return pi10;
    }

    public void setPi10(String pi10) {
        this.pi10.setText(pi10);
    }

    public JLabel getPi11() {
        return pi11;
    }

    public void setPi11(String pi11) {
        this.pi11.setText(pi11);
    }

    public JLabel getPiF00() {
        return piF00;
    }

    public void setPiF00(JLabel piF00) {
        this.piF00 = piF00;
    }

    public JLabel getPiF10() {
        return piF10;
    }

    public void setPiF10(JLabel piF10) {
        this.piF10 = piF10;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundNode;
    private javax.swing.JLabel belief00;
    private javax.swing.JLabel belief10;
    private javax.swing.JLabel lambda00;
    private javax.swing.JLabel lambda10;
    private javax.swing.JLabel nameNode;
    private javax.swing.JLabel pi00;
    private javax.swing.JLabel pi01;
    private javax.swing.JLabel pi10;
    private javax.swing.JLabel pi11;
    private javax.swing.JLabel piF00;
    private javax.swing.JLabel piF10;
    // End of variables declaration//GEN-END:variables
}
